import type { TraceRuntimeTargetDefinition } from "./types"

export const TRACE_RUNTIME_TARGETS: TraceRuntimeTargetDefinition[] = [
  {
    id: "trace-design",
    kind: "SKILL",
    label: "TRACE Design Front Door",
    description: "Routes project context to the smallest fitting set of references, operators and next actions.",
    authority: "SUGGEST",
  },
  {
    id: "trace-studio-art-direction",
    kind: "SKILL",
    label: "Art Direction",
    description: "Builds a differentiated art-direction brief and prepares a reversible Project Brain design patch.",
    authority: "PREPARE",
  },
  {
    id: "trace-studio-component-router",
    kind: "SKILL",
    label: "Component Router",
    description: "Selects the smallest compatible Component Registry set and prepares a reversible registry-selection patch.",
    authority: "PREPARE",
  },
  {
    id: "trace-studio-creative-director",
    kind: "SKILL",
    label: "Creative Director",
    description: "Locks a bounded design direction and returns one next move without silently expanding authority.",
    authority: "SUGGEST",
  },
  {
    id: "trace-studio-design-system",
    kind: "SKILL",
    label: "Design System",
    description: "Audits coherence across tokens, components, responsive behavior and accessibility strategy.",
    authority: "PREPARE",
  },
  {
    id: "trace-studio-flow",
    kind: "SKILL",
    label: "Product Flow",
    description: "Reviews product flow and prepares interaction, responsive and accessibility guidance.",
    authority: "PREPARE",
  },
  {
    id: "trace-studio-motion",
    kind: "SKILL",
    label: "Motion",
    description: "Builds a motion contract with reduced-motion constraints and prepares a reversible interaction patch.",
    authority: "PREPARE",
  },
  {
    id: "trace-studio-runtime-review",
    kind: "SKILL",
    label: "Runtime Review",
    description: "Executes a runtime-oriented review and prepares auditable Project Brain audit results.",
    authority: "PREPARE",
  },
  {
    id: "trace-studio-assurance-review",
    kind: "SKILL",
    label: "Assurance Review",
    description: "Runs Design / Experience Assurance and returns pass/hold/rework findings.",
    authority: "SUGGEST",
  },
  {
    id: "trace-studio-evidence",
    kind: "SKILL",
    label: "Evidence",
    description: "Creates a durable evidence artifact, prepares Project Brain evidence, and can prepare a GitHub evidence branch.",
    authority: "PREPARE",
  },
  {
    id: "trace-studio-gate",
    kind: "SKILL",
    label: "Gate",
    description: "Evaluates promotion readiness without auto-promoting the project.",
    authority: "SUGGEST",
  },
  {
    id: "trace-studio-next",
    kind: "SKILL",
    label: "Next Move",
    description: "Returns exactly one bounded next move from current project and routing evidence.",
    authority: "SUGGEST",
  },
  {
    id: "trace-studio-status",
    kind: "SKILL",
    label: "Status",
    description: "Produces a live status projection from Project Brain and the TRACE Design route.",
    authority: "SUGGEST",
  },
  {
    id: "trace-assurance-review",
    kind: "SKILL",
    label: "Stable Assurance Review",
    description: "Stable read-only assurance execution path.",
    authority: "SUGGEST",
    delegatesTo: "trace-studio-assurance-review",
  },
  {
    id: "trace-evidence",
    kind: "SKILL",
    label: "Stable Evidence",
    description: "Stable evidence execution path.",
    authority: "PREPARE",
    delegatesTo: "trace-studio-evidence",
  },
  {
    id: "trace-gate",
    kind: "SKILL",
    label: "Stable Gate",
    description: "Stable promotion-gate execution path.",
    authority: "SUGGEST",
    delegatesTo: "trace-studio-gate",
  },
  {
    id: "trace-next",
    kind: "SKILL",
    label: "Stable Next",
    description: "Stable next-action execution path.",
    authority: "SUGGEST",
    delegatesTo: "trace-studio-next",
  },
  {
    id: "trace-status",
    kind: "SKILL",
    label: "Stable Status",
    description: "Stable project-status execution path.",
    authority: "SUGGEST",
    delegatesTo: "trace-studio-status",
  },

  {
    id: "agent-front-door",
    kind: "AGENT",
    label: "TRACE Design Front Door",
    description: "Runs the TRACE Design routing skill as an operator.",
    authority: "SUGGEST",
    delegatesTo: "trace-design",
  },
  {
    id: "agent-creative-director",
    kind: "AGENT",
    label: "Creative Director Agent",
    description: "Runs the bounded Creative Director skill.",
    authority: "SUGGEST",
    delegatesTo: "trace-studio-creative-director",
  },
  {
    id: "agent-art-direction",
    kind: "AGENT",
    label: "Art Direction Agent",
    description: "Runs the art-direction skill and prepares reversible design-state changes.",
    authority: "PREPARE",
    delegatesTo: "trace-studio-art-direction",
  },
  {
    id: "agent-component-router",
    kind: "AGENT",
    label: "Component Router Agent",
    description: "Runs component selection and prepares Project Brain registry updates.",
    authority: "PREPARE",
    delegatesTo: "trace-studio-component-router",
  },
  {
    id: "agent-runtime-reviewer",
    kind: "AGENT",
    label: "Runtime Reviewer Agent",
    description: "Runs runtime and accessibility review.",
    authority: "PREPARE",
    delegatesTo: "trace-studio-runtime-review",
  },
  {
    id: "agent-assurance-reviewer",
    kind: "AGENT",
    label: "Assurance Reviewer Agent",
    description: "Runs Design / Experience Assurance.",
    authority: "SUGGEST",
    delegatesTo: "trace-studio-assurance-review",
  },
  {
    id: "agent-evidence-keeper",
    kind: "AGENT",
    label: "Evidence Keeper Agent",
    description: "Runs evidence capture and preparation.",
    authority: "PREPARE",
    delegatesTo: "trace-studio-evidence",
  },
  {
    id: "agent-gate-keeper",
    kind: "AGENT",
    label: "Gate Keeper Agent",
    description: "Runs the promotion gate without auto-promoting.",
    authority: "SUGGEST",
    delegatesTo: "trace-studio-gate",
  },
  {
    id: "agent-chief-of-staff",
    kind: "AGENT",
    label: "Chief of Staff",
    description: "Adjacent orchestration projection; can sequence work but does not gain canonical-write authority.",
    authority: "SUGGEST",
    delegatesTo: "trace-studio-next",
  },
  {
    id: "agent-pbpd-builder",
    kind: "AGENT",
    label: "PBPD Builder",
    description: "Adjacent build-planning projection; routes to component and build preparation only.",
    authority: "PREPARE",
    delegatesTo: "trace-studio-component-router",
  },
  {
    id: "agent-project-finisher",
    kind: "AGENT",
    label: "Project Finisher",
    description: "Adjacent completion projection; runs assurance before any completion claim.",
    authority: "SUGGEST",
    delegatesTo: "trace-studio-assurance-review",
  },
]

export function getTraceRuntimeTarget(kind: TraceRuntimeTargetDefinition["kind"], id: string): TraceRuntimeTargetDefinition | undefined {
  return TRACE_RUNTIME_TARGETS.find((target) => target.kind === kind && target.id === id)
}

export function getTraceRuntimeExecutableSkillId(kind: TraceRuntimeTargetDefinition["kind"], id: string): string | undefined {
  const target = getTraceRuntimeTarget(kind, id)
  if (!target) return undefined
  return target.delegatesTo ?? target.id
}
