import type { ColorToken } from "@/lib/foundations/types"

export const colorTokens: ColorToken[] = [
  {
    role: "background",
    light: "#f3efe6",
    dark: "#121110",
    usage: "App canvas and large backdrop fields.",
    recommendedCombinations: ["text-primary", "border-subtle", "surface"],
    limitations: ["Not intended for content cards.", "Avoid using as a brand accent."],
  },
  {
    role: "surface",
    light: "#fbfaf6",
    dark: "#1a1816",
    usage: "Primary readable panels and specimen surfaces.",
    recommendedCombinations: ["text-primary", "border-default", "surface-raised"],
    limitations: ["Can flatten if used everywhere.", "Needs border contrast in dense layouts."],
  },
  {
    role: "surface-raised",
    light: "#eae6db",
    dark: "#22201d",
    usage: "Secondary panels, control groups, and supporting blocks.",
    recommendedCombinations: ["text-primary", "border-default", "surface"],
    limitations: ["Should stay subtler than raised cards.", "Do not use for critical callouts."],
  },
  {
    role: "surface-inverse",
    light: "#121110",
    dark: "#f3efe6",
    usage: "Inverse sections, dark callouts, and flipped panels.",
    recommendedCombinations: ["text-inverse", "border-subtle", "accent"],
    limitations: ["Requires careful contrast review.", "Best limited to strong sectional moments."],
  },
  {
    role: "text-primary",
    light: "#181716",
    dark: "#f5f3ee",
    usage: "Primary reading text and headings.",
    recommendedCombinations: ["background", "surface", "surface-raised"],
    limitations: ["Avoid on highly saturated accents.", "Use moderate line length for comfort."],
  },
  {
    role: "text-secondary",
    light: "#4f4a44",
    dark: "#c7c0b5",
    usage: "Secondary labels and supporting copy.",
    recommendedCombinations: ["surface", "background", "border-default"],
    limitations: ["Not suitable for long-form body on low-contrast backgrounds."],
  },
  {
    role: "text-muted",
    light: "#7a756c",
    dark: "#a8a195",
    usage: "Meta labels, annotations, and supporting legends.",
    recommendedCombinations: ["surface", "surface-raised", "surface-inverse"],
    limitations: ["Avoid for body copy.", "Should not carry meaning alone."],
  },
  {
    role: "text-inverse",
    light: "#f5f3ee",
    dark: "#181716",
    usage: "Text on inverse surfaces.",
    recommendedCombinations: ["surface-inverse", "accent", "border-subtle"],
    limitations: ["Needs the inverse surface context.", "Avoid on neutral light surfaces."],
  },
  {
    role: "border-subtle",
    light: "#d7d1c6",
    dark: "#3a3732",
    usage: "Quiet dividers and framing lines.",
    recommendedCombinations: ["surface", "surface-raised", "background"],
    limitations: ["Too weak for interactive affordances."],
  },
  {
    role: "border-default",
    light: "#b8b0a3",
    dark: "#4c483f",
    usage: "Default component borders and control framing.",
    recommendedCombinations: ["surface", "surface-raised", "text-primary"],
    limitations: ["Can overwhelm subtle surfaces if repeated too often."],
  },
  {
    role: "border-strong",
    light: "#5f5850",
    dark: "#91897c",
    usage: "Strong separators and deliberate emphasis lines.",
    recommendedCombinations: ["surface-inverse", "surface", "accent"],
    limitations: ["Use sparingly to avoid heavy framing."],
  },
  {
    role: "accent",
    light: "#0f766e",
    dark: "#47d6c7",
    usage: "Primary interactive highlight and key markers.",
    recommendedCombinations: ["surface", "surface-inverse", "text-primary"],
    limitations: ["Should not be the only cue for state.", "Avoid large blocks of accent fill."],
  },
  {
    role: "success",
    light: "#15803d",
    dark: "#4ade80",
    usage: "Positive status and confirmation states.",
    recommendedCombinations: ["surface", "surface-inverse", "text-primary"],
    limitations: ["Use for status, not decoration."],
  },
  {
    role: "warning",
    light: "#b45309",
    dark: "#f59e0b",
    usage: "Cautionary states and advisory messages.",
    recommendedCombinations: ["surface", "surface-inverse", "text-primary"],
    limitations: ["Should stay secondary to content hierarchy."],
  },
  {
    role: "danger",
    light: "#b91c1c",
    dark: "#f87171",
    usage: "Critical errors and destructive states.",
    recommendedCombinations: ["surface", "surface-inverse", "text-inverse"],
    limitations: ["Reserve for actual destructive or error states."],
  },
  {
    role: "info",
    light: "#1d4ed8",
    dark: "#60a5fa",
    usage: "Informational notes and neutral guidance.",
    recommendedCombinations: ["surface", "surface-raised", "text-primary"],
    limitations: ["Avoid replacing core hierarchy."],
  },
]
