// ─────────────────────────────────────────────────────────────
// Playbook Knowledge System — Editorial Metadata Overlays
// ─────────────────────────────────────────────────────────────
// CLIENT-SAFE. No fs. No Markdown text. No hashes.
// Only editorial data absent from the manifest.
// Covers all 61 public entries.
// ─────────────────────────────────────────────────────────────

import type { PlaybookMetadataOverlay } from "./types"

// ── Raw overlays indexed by publicTargetPath ─────────────────
type OverlayInput = Omit<PlaybookMetadataOverlay, "slug" | "slugSegments">

const rawOverlays: OverlayInput[] = [
  // ── POSITIONING-JUDGING ──────────────────────────────────
  {
    id: "system-principles",
    collectionId: "positioning-judging",
    format: "principle",
    phases: ["position", "design", "build", "present"],
    audiences: ["hackathon-builder", "judge-facing-team", "product-designer"],
    outcomes: ["judge-clarity", "positioning"],
    tags: ["principles", "judge", "structure", "proof", "polish"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["judge-path", "proof-moment-pattern", "checklists"],
    relatedRegistryIds: ["decision-systems"],
    recommendedFor: ["Every hackathon project start", "Pre-submission review"],
    limitations: ["Very concise — intended as a reference card, not a method guide"],
  },
  {
    id: "judge-path",
    collectionId: "positioning-judging",
    format: "principle",
    phases: ["position", "present", "submit"],
    audiences: ["hackathon-builder", "judge-facing-team", "submission-lead"],
    outcomes: ["judge-clarity", "positioning"],
    tags: ["judge", "path", "problem", "promise", "evidence", "sponsor"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["system-principles", "proof-moment-pattern", "judge-memory-sentence"],
    relatedRegistryIds: ["decision-systems"],
    recommendedFor: ["Submission review", "Demo scripting"],
    limitations: ["Assumes linear judge evaluation — actual judging may vary"],
  },
  {
    id: "landing-blueprint",
    collectionId: "uiux",
    format: "blueprint",
    phases: ["design", "build"],
    audiences: ["ui-designer", "product-designer", "hackathon-builder"],
    outcomes: ["interface-architecture", "judge-clarity"],
    tags: ["landing", "hero", "evidence", "blueprint", "layout"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["dashboard-blueprint", "composition-rules", "responsive-rules"],
    relatedRegistryIds: ["layouts", "product-launch-recipe"],
    recommendedFor: ["Landing page design", "First-screen architecture"],
    limitations: ["Blueprint structure — visual implementation requires Color System and Typography System"],
  },
  {
    id: "dashboard-blueprint",
    collectionId: "uiux",
    format: "blueprint",
    phases: ["design", "build"],
    audiences: ["ui-designer", "product-designer", "hackathon-builder", "developer"],
    outcomes: ["interface-architecture", "judge-clarity"],
    tags: ["dashboard", "input", "action", "result", "evidence", "blueprint"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["landing-blueprint", "evidence-cards", "composition-rules"],
    relatedRegistryIds: ["decision-systems", "operational-workspace-recipe"],
    recommendedFor: ["Dashboard design", "Proof moment interfaces"],
    limitations: ["Assumes action-oriented dashboard — adapt for display-only interfaces"],
  },
  {
    id: "evidence-cards",
    collectionId: "uiux",
    format: "pattern",
    phases: ["design", "build", "verify"],
    audiences: ["ui-designer", "product-designer", "hackathon-builder", "developer"],
    outcomes: ["evidence", "judge-clarity", "technical-proof"],
    tags: ["evidence", "cards", "claim", "status", "verification", "timestamp"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["proof-moment-pattern", "dashboard-blueprint", "hackathon-evidence"],
    relatedRegistryIds: ["decision-systems", "evidence-ledger", "capture-bridge"],
    recommendedFor: ["Evidence display", "Proof visibility", "Status cards"],
    limitations: ["Card structure must be paired with real evidence — do not use with simulated results"],
  },
  {
    id: "demo-video-script",
    collectionId: "demo-video",
    format: "script",
    phases: ["present", "submit"],
    audiences: ["demo-producer", "video-editor", "hackathon-builder", "submission-lead"],
    outcomes: ["demo-script", "video-production", "judge-clarity"],
    tags: ["demo", "video", "script", "timing", "60s", "judge", "evidence"],
    maturity: "active",
    ecosystemTarget: "universal-demo-film-kit",
    relatedPlaybookIds: ["hackathon-demo", "hackathon-video-egaki", "proof-moment-pattern"],
    relatedRegistryIds: ["interaction-player", "capture-bridge", "product-launch-recipe"],
    recommendedFor: ["Demo video production", "Submission video scripting"],
    limitations: [
      "Timing assumes live demo — adjust for screen recordings",
      "Future Universal Demo Film Kit layer not yet implemented",
    ],
    futureTarget: "universal-demo-film-kit",
  },
  {
    id: "typography-system",
    collectionId: "uiux",
    format: "system",
    phases: ["design", "build"],
    audiences: ["ui-designer", "product-designer", "creative-director", "hackathon-builder"],
    outcomes: ["visual-direction", "judge-clarity"],
    tags: ["typography", "font", "hero", "evidence", "trust", "memory", "inter", "geist"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["color-system", "component-rules", "anti-ai-slop-pass"],
    relatedRegistryIds: ["typography", "foundations"],
    recommendedFor: ["Font selection", "UI type hierarchy", "Hero identity"],
    limitations: ["Font availability depends on project tech stack and licensing"],
  },
  {
    id: "color-system",
    collectionId: "uiux",
    format: "system",
    phases: ["design", "build"],
    audiences: ["ui-designer", "product-designer", "creative-director", "hackathon-builder"],
    outcomes: ["visual-direction", "judge-clarity"],
    tags: ["color", "palette", "role", "signal", "contrast", "trust"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["typography-system", "component-rules", "controlled-visual-risk"],
    relatedRegistryIds: ["foundations"],
    recommendedFor: ["Color palette definition", "Signal/background/accent roles"],
    limitations: ["Does not prescribe specific color values — roles must be adapted per project"],
  },
  {
    id: "component-rules",
    collectionId: "uiux",
    format: "principle",
    phases: ["design", "build"],
    audiences: ["ui-designer", "developer", "hackathon-builder"],
    outcomes: ["interface-architecture", "judge-clarity"],
    tags: ["components", "buttons", "CTAs", "verbs", "clarity", "rules"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["responsive-rules", "composition-rules", "typography-system"],
    relatedRegistryIds: ["foundations", "layouts"],
    recommendedFor: ["Button and CTA design", "Interface component vocabulary"],
    limitations: ["UI-layer rules only — not a component architecture guide"],
  },
  {
    id: "responsive-rules",
    collectionId: "uiux",
    format: "principle",
    phases: ["design", "build"],
    audiences: ["ui-designer", "developer", "hackathon-builder"],
    outcomes: ["responsive-design", "interface-architecture"],
    tags: ["responsive", "mobile", "tablet", "breakpoints", "layout", "readability"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["composition-rules", "component-rules", "dashboard-blueprint"],
    relatedRegistryIds: ["layouts"],
    recommendedFor: ["Mobile-first interface design", "Breakpoint decisions"],
    limitations: ["Mobile is not squeezed desktop — must be designed separately"],
  },
  {
    id: "composition-rules",
    collectionId: "uiux",
    format: "principle",
    phases: ["design", "build"],
    audiences: ["ui-designer", "product-designer", "creative-director", "hackathon-builder"],
    outcomes: ["visual-direction", "interface-architecture", "judge-clarity"],
    tags: ["composition", "attention", "hierarchy", "whitespace", "layout", "judge"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["typography-system", "responsive-rules", "controlled-visual-risk"],
    relatedRegistryIds: ["layouts", "foundations"],
    recommendedFor: ["Page composition decisions", "Visual hierarchy control"],
    limitations: ["Applies primarily to screen-based interfaces — adapt for video/broadcast"],
  },
  {
    id: "design-prompts",
    collectionId: "positioning-judging",
    format: "prompt-set",
    phases: ["design", "build"],
    audiences: ["ui-designer", "product-designer", "hackathon-builder"],
    outcomes: ["visual-direction", "judge-clarity", "interface-architecture"],
    tags: ["prompts", "judge", "hierarchy", "evidence", "anti-slop", "creative-direction"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["anti-ai-slop-pass", "controlled-visual-risk", "system-principles"],
    relatedRegistryIds: ["foundations"],
    recommendedFor: ["AI-assisted design direction", "Visual hierarchy correction"],
    limitations: ["Prompt effectiveness depends on the AI model and context window"],
  },
  {
    id: "checklists",
    collectionId: "positioning-judging",
    format: "checklist",
    phases: ["verify", "audit", "present", "submit"],
    audiences: ["hackathon-builder", "submission-lead", "judge-facing-team"],
    outcomes: ["judge-clarity", "audit", "evidence"],
    tags: ["checklist", "5-second", "judge", "video", "visual-polish", "clarity"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["system-principles", "judge-path", "hackathon-audit"],
    relatedRegistryIds: ["decision-systems"],
    recommendedFor: ["Pre-submission verification", "Demo readiness check"],
    limitations: ["Checklist items require human judgment — not automatable"],
  },
  {
    id: "positioning-system",
    collectionId: "positioning-judging",
    format: "system",
    phases: ["qualify", "position", "differentiate"],
    audiences: ["hackathon-builder", "founder", "judge-facing-team", "product-designer"],
    outcomes: ["positioning", "differentiation", "judge-clarity"],
    tags: ["positioning", "system", "screen", "pitch", "brand", "differentiation"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["problem-tension-canvas", "hook-library", "hero-copy-system"],
    relatedRegistryIds: [],
    recommendedFor: ["Project positioning strategy", "Differentiation from other submissions"],
    limitations: ["Hackathon-scoped — adapt for product or go-to-market contexts"],
  },
  {
    id: "problem-tension-canvas",
    collectionId: "positioning-judging",
    format: "method",
    phases: ["qualify", "research", "position"],
    audiences: ["hackathon-builder", "founder", "product-designer", "ux-researcher"],
    outcomes: ["positioning", "differentiation", "research"],
    tags: ["problem", "tension", "canvas", "insight", "framing", "visible"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["positioning-system", "hook-library", "hackathon-intake"],
    relatedRegistryIds: [],
    recommendedFor: ["Problem framing", "Project kickoff", "Pre-design positioning"],
    limitations: ["Requires honest assessment of the problem — not a validation shortcut"],
  },
  {
    id: "hook-library",
    collectionId: "positioning-judging",
    format: "system",
    phases: ["position", "differentiate", "present"],
    audiences: ["hackathon-builder", "judge-facing-team", "creative-director", "founder"],
    outcomes: ["positioning", "judge-clarity", "hero-copy", "differentiation"],
    tags: ["hook", "compression", "judge", "memory", "copy", "promise"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["judge-memory-sentence", "hero-copy-system", "problem-tension-canvas"],
    relatedRegistryIds: [],
    recommendedFor: ["Project hook writing", "Landing hero copy", "Demo opener"],
    limitations: ["Hooks require a real insight — cannot be generated without understanding the project"],
  },
  {
    id: "social-launch-pack",
    collectionId: "positioning-judging",
    format: "launch-pack",
    phases: ["launch"],
    audiences: ["hackathon-builder", "founder", "judge-facing-team"],
    outcomes: ["social-launch", "positioning", "judge-clarity"],
    tags: ["social", "launch", "judge", "surface", "post", "github", "portfolio"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hero-copy-system", "hook-library", "hackathon-submission"],
    relatedRegistryIds: ["product-launch-recipe"],
    recommendedFor: ["Post-submission public announcement", "Portfolio packaging"],
    limitations: ["Requires a submitted, demonstrable project"],
  },
  {
    id: "judge-memory-sentence",
    collectionId: "positioning-judging",
    format: "method",
    phases: ["position", "differentiate", "present"],
    audiences: ["hackathon-builder", "judge-facing-team", "creative-director"],
    outcomes: ["judge-clarity", "positioning", "hero-copy"],
    tags: ["judge", "memory", "sentence", "recall", "one-liner", "clarity"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["hook-library", "hero-copy-system", "positioning-system"],
    relatedRegistryIds: [],
    recommendedFor: ["Project summary writing", "Submission tagline", "Demo opener line"],
    limitations: ["The sentence must reflect a real, demonstrable capability"],
  },
  {
    id: "proof-moment-pattern",
    collectionId: "positioning-judging",
    format: "pattern",
    phases: ["design", "build", "verify", "present"],
    audiences: ["ui-designer", "developer", "hackathon-builder", "judge-facing-team"],
    outcomes: ["evidence", "technical-proof", "judge-clarity", "interaction-design"],
    tags: ["proof", "moment", "pattern", "verdict", "receipt", "visible", "input", "output"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["evidence-cards", "dashboard-blueprint", "checklists"],
    relatedRegistryIds: ["decision-systems", "capture-bridge", "evidence-ledger"],
    recommendedFor: ["Proof moment interface design", "Evidence visibility", "Judge clarity"],
    limitations: ["Pattern requires real technical output to display — not for simulated results"],
  },
  {
    id: "hero-copy-system",
    collectionId: "positioning-judging",
    format: "system",
    phases: ["position", "design", "present"],
    audiences: ["hackathon-builder", "creative-director", "judge-facing-team", "founder"],
    outcomes: ["hero-copy", "positioning", "judge-clarity"],
    tags: ["hero", "copy", "headline", "compression", "project", "tagline"],
    maturity: "foundational",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["hook-library", "judge-memory-sentence", "positioning-system"],
    relatedRegistryIds: ["product-launch-recipe"],
    recommendedFor: ["Hero section copy", "Submission headline", "Project summary"],
    limitations: ["Copy must be grounded in real capability — not aspirational"],
  },
  {
    id: "positioning-prompts",
    collectionId: "positioning-judging",
    format: "prompt-set",
    phases: ["position", "differentiate"],
    audiences: ["hackathon-builder", "founder", "product-designer"],
    outcomes: ["positioning", "differentiation", "hero-copy"],
    tags: ["prompts", "positioning", "tension", "hook", "differentiation"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["problem-tension-canvas", "hook-library", "positioning-system"],
    relatedRegistryIds: [],
    recommendedFor: ["AI-assisted positioning", "Hook generation"],
    limitations: ["Prompt results depend on quality of project context provided"],
  },
  {
    id: "ai-design-stack",
    collectionId: "positioning-judging",
    format: "reference",
    phases: ["design", "build"],
    audiences: ["ui-designer", "product-designer", "developer", "hackathon-builder"],
    outcomes: ["visual-direction", "interface-architecture", "research"],
    tags: ["ai", "design", "stack", "tools", "ui-kit", "references", "libraries"],
    maturity: "reference",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["controlled-visual-risk", "anti-ai-slop-pass", "reference-to-polished-ui"],
    relatedRegistryIds: ["foundations"],
    recommendedFor: ["Tool selection for AI-assisted design", "Resource mapping"],
    limitations: ["Tool landscape evolves rapidly — verify availability and pricing"],
  },
  {
    id: "reference-to-polished-ui",
    collectionId: "uiux",
    format: "method",
    phases: ["design", "build"],
    audiences: ["ui-designer", "creative-director", "hackathon-builder"],
    outcomes: ["visual-direction", "interface-architecture"],
    tags: ["reference", "polished", "ui", "screenshots", "templates", "non-generic", "inspiration"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["controlled-visual-risk", "anti-ai-slop-pass", "ai-design-stack"],
    relatedRegistryIds: ["foundations"],
    recommendedFor: ["Visual direction from references", "Moving beyond generic outputs"],
    limitations: ["References must be used as inspiration signals, not as direct copy"],
  },
  {
    id: "anti-ai-slop-pass",
    collectionId: "uiux",
    format: "method",
    phases: ["design", "build", "verify"],
    audiences: ["ui-designer", "product-designer", "hackathon-builder"],
    outcomes: ["visual-direction", "judge-clarity"],
    tags: ["anti-slop", "generic", "ai", "correction", "polish", "detection"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["controlled-visual-risk", "reference-to-polished-ui", "design-prompts"],
    relatedRegistryIds: ["foundations"],
    recommendedFor: ["Detecting generic AI outputs", "Visual polish pass", "Pre-submission UI review"],
    limitations: ["Requires human judgment for detection — not automatable"],
  },
  {
    id: "controlled-visual-risk",
    collectionId: "uiux",
    format: "method",
    phases: ["design", "differentiate"],
    audiences: ["ui-designer", "creative-director", "product-designer", "hackathon-builder"],
    outcomes: ["visual-direction", "differentiation"],
    tags: ["visual-risk", "bold", "signature", "typography", "color", "motion", "distinctive"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["anti-ai-slop-pass", "reference-to-polished-ui", "composition-rules"],
    relatedRegistryIds: ["foundations", "layouts"],
    recommendedFor: ["Visual differentiation", "Signature design moments", "Avoiding safe/generic UI"],
    limitations: ["Risk budget must remain controlled — max 1-3 areas of boldness"],
  },
  {
    id: "ux-research-methods",
    collectionId: "uiux",
    format: "method",
    phases: ["qualify", "research", "design"],
    audiences: ["ux-researcher", "product-designer", "hackathon-builder"],
    outcomes: ["research", "positioning", "interface-architecture"],
    tags: ["ux", "research", "validation", "methods", "lightweight", "assumptions"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["problem-tension-canvas", "hackathon-research", "hackathon-landscape"],
    relatedRegistryIds: [],
    recommendedFor: ["Lightweight UX validation", "Design decision grounding"],
    limitations: ["Lightweight methods — not a substitute for full user research"],
  },
  {
    id: "judge-visual-moment",
    collectionId: "positioning-judging",
    format: "system",
    phases: ["design", "build", "present"],
    audiences: ["ui-designer", "creative-director", "hackathon-builder", "judge-facing-team"],
    outcomes: ["visual-direction", "judge-clarity", "differentiation"],
    tags: ["visual", "memory", "moment", "judge", "controlled", "distinctive", "layer"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["controlled-visual-risk", "proof-moment-pattern", "composition-rules"],
    relatedRegistryIds: ["foundations", "product-launch-recipe"],
    recommendedFor: ["Creating a memorable visual moment for judges", "Visual memory design"],
    limitations: ["Requires restraint — one visual moment, not a full redesign"],
  },
  {
    id: "uiux-readme",
    collectionId: "positioning-judging",
    format: "reference",
    phases: ["qualify"],
    audiences: ["hackathon-builder", "product-designer"],
    outcomes: ["research", "positioning"],
    tags: ["readme", "system", "overview", "index", "uiux"],
    maturity: "reference",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["system-principles", "judge-path"],
    relatedRegistryIds: [],
    recommendedFor: ["System onboarding", "Quick orientation to the UI/UX system"],
    limitations: ["Index document — does not contain full method content"],
  },
  // ── VISUAL REFERENCES ────────────────────────────────────
  {
    id: "batchguard-style",
    collectionId: "visual-references",
    format: "reference",
    phases: ["design"],
    audiences: ["ui-designer", "creative-director"],
    outcomes: ["visual-direction"],
    tags: ["batchguard", "style", "signal", "depth", "reference", "palette"],
    maturity: "reference",
    ecosystemTarget: "reference-only",
    relatedPlaybookIds: ["controlled-visual-risk", "reference-to-polished-ui"],
    relatedRegistryIds: ["foundations"],
    recommendedFor: ["Signal + Depth visual direction inspiration"],
    limitations: ["Project-specific reference — do not copy directly"],
  },
  {
    id: "cuppulse-style",
    collectionId: "visual-references",
    format: "reference",
    phases: ["design"],
    audiences: ["ui-designer", "creative-director"],
    outcomes: ["visual-direction"],
    tags: ["cuppulse", "style", "signal", "edge", "reference"],
    maturity: "reference",
    ecosystemTarget: "reference-only",
    relatedPlaybookIds: ["controlled-visual-risk", "reference-to-polished-ui"],
    relatedRegistryIds: ["foundations"],
    recommendedFor: ["Signal + Edge visual direction inspiration"],
    limitations: ["Project-specific reference — do not copy directly"],
  },
  {
    id: "edgevoc-style",
    collectionId: "visual-references",
    format: "reference",
    phases: ["design"],
    audiences: ["ui-designer", "creative-director"],
    outcomes: ["visual-direction"],
    tags: ["edgevoc", "style", "depth", "reference"],
    maturity: "reference",
    ecosystemTarget: "reference-only",
    relatedPlaybookIds: ["controlled-visual-risk", "reference-to-polished-ui"],
    relatedRegistryIds: ["foundations"],
    recommendedFor: ["Depth-first visual direction inspiration"],
    limitations: ["Project-specific reference — do not copy directly"],
  },
  {
    id: "local-business-fix-lab-style",
    collectionId: "visual-references",
    format: "reference",
    phases: ["design"],
    audiences: ["ui-designer", "creative-director"],
    outcomes: ["visual-direction"],
    tags: ["local-business", "fix-lab", "edge", "business", "reference"],
    maturity: "reference",
    ecosystemTarget: "reference-only",
    relatedPlaybookIds: ["controlled-visual-risk", "reference-to-polished-ui"],
    relatedRegistryIds: ["foundations"],
    recommendedFor: ["Edge + Business visual direction inspiration"],
    limitations: ["Project-specific reference — do not copy directly"],
  },
  // ── HACKATHON EVIDENCE ───────────────────────────────────
  {
    id: "hackathon-evidence",
    collectionId: "hackathon-evidence",
    format: "operating-module",
    phases: ["verify", "audit", "submit"],
    audiences: ["hackathon-builder", "submission-lead", "developer", "judge-facing-team"],
    outcomes: ["evidence", "technical-proof", "submission"],
    tags: ["evidence", "taxonomy", "classification", "claim", "source", "confidence", "proof"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["evidence-cards", "proof-moment-pattern", "hackathon-audit", "hackathon-submission"],
    relatedRegistryIds: ["decision-systems", "evidence-ledger", "capture-bridge"],
    recommendedFor: ["Evidence collection and classification", "Pre-audit evidence review"],
    limitations: ["Evidence quality is bounded by the actual technical outputs — narration does not upgrade it"],
  },
  {
    id: "hackathon-submission-package",
    collectionId: "hackathon-evidence",
    format: "template",
    phases: ["submit"],
    audiences: ["submission-lead", "hackathon-builder"],
    outcomes: ["submission"],
    tags: ["submission", "package", "assets", "final"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-submission", "hackathon-audit", "hackathon-evidence"],
    relatedRegistryIds: [],
    recommendedFor: ["Final submission packaging"],
    limitations: ["Template structure — content must come from completed phases"],
  },
  {
    id: "hackathon-submission",
    collectionId: "hackathon-evidence",
    format: "operating-module",
    phases: ["submit"],
    audiences: ["submission-lead", "hackathon-builder", "judge-facing-team"],
    outcomes: ["submission", "judge-clarity", "evidence"],
    tags: ["submission", "judge", "package", "evidence", "demo", "technical-proof", "complete"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-audit", "hackathon-evidence", "hackathon-submission-package"],
    relatedRegistryIds: ["decision-systems", "capture-bridge"],
    recommendedFor: ["Complete submission creation", "Judge-facing package assembly"],
    limitations: ["Requires completed audit gate before submission"],
  },
  // ── HACKATHON GATES ──────────────────────────────────────
  {
    id: "hackathon-angle-mort",
    collectionId: "hackathon-gates",
    format: "gate",
    phases: ["differentiate", "verify", "audit"],
    audiences: ["hackathon-builder", "submission-lead"],
    outcomes: ["differentiation", "audit"],
    tags: ["angle-mort", "blind-spot", "strategic", "challenge", "optional"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-audit", "hackathon-distinction", "hackathon-operating-gates"],
    relatedRegistryIds: [],
    recommendedFor: ["Blind spot detection", "Strategic challenge before submission"],
    limitations: ["Optional gate — use when the project feels strategically safe or unchallenged"],
  },
  {
    id: "hackathon-audit",
    collectionId: "hackathon-gates",
    format: "gate",
    phases: ["audit", "submit"],
    audiences: ["submission-lead", "hackathon-builder", "judge-facing-team"],
    outcomes: ["audit", "submission", "judge-clarity"],
    tags: ["audit", "go-no-go", "eligibility", "compliance", "distinction", "evidence", "demo"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-operating-gates", "hackathon-evidence", "hackathon-submission", "checklists"],
    relatedRegistryIds: ["decision-systems", "decision-gate"],
    recommendedFor: ["Final go/no-go decision", "Pre-submission readiness check"],
    limitations: ["Audit may return NO-GO — must be willing to delay or withdraw"],
  },
  {
    id: "hackathon-distinction",
    collectionId: "hackathon-gates",
    format: "gate",
    phases: ["differentiate", "verify", "audit"],
    audiences: ["hackathon-builder", "submission-lead", "creative-director"],
    outcomes: ["differentiation", "judge-clarity", "audit"],
    tags: ["distinction", "differentiation", "memorable", "credible", "polish"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-audit", "hackathon-naming-distinction", "positioning-system"],
    relatedRegistryIds: [],
    recommendedFor: ["Moving from functional to memorable", "Distinction review"],
    limitations: ["Distinction cannot be applied last-minute without design time"],
  },
  {
    id: "hackathon-naming-distinction",
    collectionId: "hackathon-gates",
    format: "gate",
    phases: ["differentiate"],
    audiences: ["hackathon-builder", "founder", "creative-director"],
    outcomes: ["naming", "differentiation"],
    tags: ["naming", "distinction", "product-name", "credible", "memorable", "anti-generic"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-distinction", "positioning-system", "hero-copy-system"],
    relatedRegistryIds: [],
    recommendedFor: ["Product naming", "Anti-generic name generation"],
    limitations: ["Name must be validated against hackathon rules for trademark/IP"],
  },
  {
    id: "hackathon-operating-gates",
    collectionId: "hackathon-gates",
    format: "gate",
    phases: ["verify", "present", "submit"],
    audiences: ["submission-lead", "hackathon-builder", "video-editor", "demo-producer"],
    outcomes: ["video-production", "submission", "audit"],
    tags: ["operating-gates", "video", "packaging", "brag", "egaki", "judge", "submission"],
    maturity: "active",
    ecosystemTarget: "universal-demo-film-kit",
    relatedPlaybookIds: ["hackathon-audit", "hackathon-video-brag", "hackathon-video-egaki", "demo-video-script"],
    relatedRegistryIds: ["capture-bridge", "interaction-player"],
    recommendedFor: ["Final video packaging gate", "Pre-submission video decisions"],
    limitations: ["Gate requires working demo, frozen UI, and evidence before entry"],
    futureTarget: "universal-demo-film-kit",
  },
  // ── HACKATHON TEMPLATES ──────────────────────────────────
  {
    id: "hackathon-antigravity",
    collectionId: "hackathon-templates",
    format: "operating-module",
    phases: ["build"],
    audiences: ["hackathon-builder", "developer"],
    outcomes: ["technical-proof", "interface-architecture"],
    tags: ["antigravity", "ide", "integration", "claude", "ai", "workflow"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["hackathon-execution", "hackathon-product"],
    relatedRegistryIds: [],
    recommendedFor: ["Google Antigravity IDE integration in hackathon workflows"],
    limitations: ["Specific to Antigravity IDE — adapt for other AI development tools"],
  },
  {
    id: "hackathon-execution",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["plan", "build"],
    audiences: ["hackathon-builder", "developer", "product-designer"],
    outcomes: ["technical-proof", "interface-architecture"],
    tags: ["execution", "build", "plan", "time-box", "reliable", "distinctive"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-product-blueprint", "hackathon-product", "hackathon-intake"],
    relatedRegistryIds: ["layouts", "decision-systems"],
    recommendedFor: ["Build phase planning", "Time-boxed execution"],
    limitations: ["Requires approved Product Blueprint before starting"],
  },
  {
    id: "hackathon-funding",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["retrospective"],
    audiences: ["founder", "hackathon-builder"],
    outcomes: ["portfolio", "research"],
    tags: ["funding", "venture", "paths", "post-hackathon", "opportunity"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-venture", "hackathon-retrospective"],
    relatedRegistryIds: [],
    recommendedFor: ["Post-hackathon funding exploration"],
    limitations: ["Requires completed Venture analysis first"],
  },
  {
    id: "hackathon-idea-scorecard",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["qualify", "research"],
    audiences: ["hackathon-builder", "founder", "product-designer"],
    outcomes: ["research", "differentiation"],
    tags: ["idea", "scorecard", "candidate", "finalist", "scoring"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-ideas", "hackathon-research", "hackathon-landscape"],
    relatedRegistryIds: ["decision-systems"],
    recommendedFor: ["Idea scoring and selection", "Finalist comparison"],
    limitations: ["Scores require honest assessment — not optimization for appearances"],
  },
  {
    id: "hackathon-ideas",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["qualify", "research"],
    audiences: ["hackathon-builder", "founder", "product-designer", "ux-researcher"],
    outcomes: ["research", "positioning", "differentiation"],
    tags: ["ideas", "generate", "compare", "challenge", "select", "strategy"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-idea-scorecard", "hackathon-landscape", "hackathon-research"],
    relatedRegistryIds: [],
    recommendedFor: ["Project idea generation", "Concept selection"],
    limitations: ["Focus on strategic strength — not maximum idea count"],
  },
  {
    id: "hackathon-intake",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["qualify"],
    audiences: ["hackathon-builder", "founder", "submission-lead"],
    outcomes: ["research", "positioning"],
    tags: ["intake", "snapshot", "hackathon", "rules", "deadline", "decision-ready"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-research", "hackathon-ideas", "hackathon-landscape"],
    relatedRegistryIds: [],
    recommendedFor: ["Hackathon intake and orientation", "Rules parsing"],
    limitations: ["Output is a snapshot — must be updated as rules are clarified"],
  },
  {
    id: "hackathon-judging",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["qualify", "position"],
    audiences: ["hackathon-builder", "judge-facing-team", "submission-lead"],
    outcomes: ["judge-clarity", "positioning", "research"],
    tags: ["judging", "criteria", "scoring", "winning", "alignment"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-intake", "judge-path", "system-principles"],
    relatedRegistryIds: ["decision-systems"],
    recommendedFor: ["Judging criteria analysis", "Scoring system alignment"],
    limitations: ["Based on publicly available judging criteria — verify with official rules"],
  },
  {
    id: "hackathon-landscape",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["research", "differentiate"],
    audiences: ["hackathon-builder", "ux-researcher", "founder"],
    outcomes: ["research", "differentiation", "positioning"],
    tags: ["landscape", "competition", "analysis", "differentiation", "white-space"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-research", "hackathon-ideas", "hackathon-idea-scorecard"],
    relatedRegistryIds: [],
    recommendedFor: ["Competitive landscape analysis", "White-space identification"],
    limitations: ["Landscape analysis is time-bound — verify before submission"],
  },
  {
    id: "hackathon-loops",
    collectionId: "hackathon-templates",
    format: "operating-module",
    phases: ["build", "verify"],
    audiences: ["hackathon-builder", "developer"],
    outcomes: ["technical-proof", "interface-architecture"],
    tags: ["loops", "iteration", "improvement", "controlled", "tokens", "efficiency"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-execution", "hackathon-product"],
    relatedRegistryIds: [],
    recommendedFor: ["Controlled iteration loops", "Output improvement without token waste"],
    limitations: ["Loops must be bounded — avoid endless rewriting cycles"],
  },
  {
    id: "hackathon-portfolio",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["retrospective", "launch"],
    audiences: ["hackathon-builder", "founder", "product-designer"],
    outcomes: ["portfolio", "social-launch"],
    tags: ["portfolio", "strategic", "asset", "project", "evaluation"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-retrospective", "hackathon-venture", "social-launch-pack"],
    relatedRegistryIds: [],
    recommendedFor: ["Portfolio evaluation", "Post-hackathon asset management"],
    limitations: ["Requires honest assessment of project quality and differentiation"],
  },
  {
    id: "hackathon-product-blueprint",
    collectionId: "hackathon-templates",
    format: "blueprint",
    phases: ["plan"],
    audiences: ["hackathon-builder", "product-designer", "developer"],
    outcomes: ["interface-architecture", "technical-proof"],
    tags: ["product", "blueprint", "definition", "implementation", "selected"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-product", "hackathon-execution", "hackathon-ideas"],
    relatedRegistryIds: ["layouts", "decision-systems"],
    recommendedFor: ["Product definition freeze", "Implementation planning"],
    limitations: ["Downstream phases depend on the selected blueprint — changes are costly"],
  },
  {
    id: "hackathon-product",
    collectionId: "hackathon-templates",
    format: "operating-module",
    phases: ["plan", "design", "build"],
    audiences: ["hackathon-builder", "product-designer", "developer"],
    outcomes: ["interface-architecture", "technical-proof", "judge-clarity"],
    tags: ["product", "mvp", "credible", "judge-belief", "smallest", "viable"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-product-blueprint", "hackathon-execution", "hackathon-ideas"],
    relatedRegistryIds: ["layouts", "decision-systems", "operational-workspace-recipe"],
    recommendedFor: ["Product design phase", "MVP scoping"],
    limitations: ["Must produce judge belief — not maximum feature count"],
  },
  {
    id: "hackathon-research",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["research"],
    audiences: ["hackathon-builder", "ux-researcher", "founder"],
    outcomes: ["research", "evidence", "positioning"],
    tags: ["research", "evidence", "verify", "compress", "external", "decisions"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-landscape", "hackathon-ideas", "hackathon-intake"],
    relatedRegistryIds: [],
    recommendedFor: ["External evidence gathering", "Decision-critical research"],
    limitations: ["Research must be compressed and decision-relevant — not general background"],
  },
  {
    id: "hackathon-retrospective",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["retrospective"],
    audiences: ["hackathon-builder", "founder", "submission-lead"],
    outcomes: ["retrospective", "portfolio"],
    tags: ["retrospective", "learning", "reusable", "strategic", "convert"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-portfolio", "hackathon-venture", "hackathon-submission"],
    relatedRegistryIds: [],
    recommendedFor: ["Post-submission retrospective", "Converting hackathon into learning"],
    limitations: ["Retrospective value depends on honest, un-defensive review"],
  },
  {
    id: "hackathon-venture",
    collectionId: "hackathon-templates",
    format: "template",
    phases: ["retrospective"],
    audiences: ["founder", "hackathon-builder"],
    outcomes: ["research", "portfolio"],
    tags: ["venture", "prototype", "real-world", "opportunity", "post-hackathon"],
    maturity: "active",
    ecosystemTarget: "shared",
    relatedPlaybookIds: ["hackathon-funding", "hackathon-retrospective", "hackathon-portfolio"],
    relatedRegistryIds: [],
    recommendedFor: ["Venture potential assessment", "Post-hackathon opportunity evaluation"],
    limitations: ["Requires completed hackathon — not for pre-submission use"],
  },
  // ── HACKATHON UX/UI ──────────────────────────────────────
  {
    id: "hackathon-demo",
    collectionId: "hackathon-ux-ui",
    format: "operating-module",
    phases: ["present", "submit"],
    audiences: ["hackathon-builder", "demo-producer", "judge-facing-team", "submission-lead"],
    outcomes: ["demo-script", "judge-clarity", "video-production"],
    tags: ["demo", "judge", "clear", "credible", "memorable", "demonstration"],
    maturity: "active",
    ecosystemTarget: "universal-demo-film-kit",
    relatedPlaybookIds: ["demo-video-script", "hackathon-visual-production", "hackathon-video-egaki", "hackathon-ui-polish"],
    relatedRegistryIds: ["capture-bridge", "product-launch-recipe", "broadcast-package-recipe", "interaction-player"],
    recommendedFor: ["Demo production", "Submission demo packaging"],
    limitations: ["Demo must show working product — simulations require explicit labels"],
    futureTarget: "universal-demo-film-kit",
  },
  {
    id: "hackathon-ui-polish",
    collectionId: "hackathon-ux-ui",
    format: "operating-module",
    phases: ["build", "verify"],
    audiences: ["ui-designer", "hackathon-builder"],
    outcomes: ["visual-direction", "judge-clarity", "interface-architecture"],
    tags: ["ui-polish", "polish", "mandatory", "conditional", "refinement"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["anti-ai-slop-pass", "controlled-visual-risk", "hackathon-ux"],
    relatedRegistryIds: ["foundations", "layouts"],
    recommendedFor: ["UI polish pass", "Pre-demo visual refinement"],
    limitations: ["Polish must follow working happy path — not applied before functionality"],
  },
  {
    id: "hackathon-ux",
    collectionId: "hackathon-ux-ui",
    format: "operating-module",
    phases: ["design"],
    audiences: ["ux-researcher", "ui-designer", "hackathon-builder", "product-designer"],
    outcomes: ["interaction-design", "interface-architecture", "judge-clarity"],
    tags: ["ux", "design", "understandable", "credible", "distinctive", "memorable"],
    maturity: "active",
    ecosystemTarget: "componentry",
    relatedPlaybookIds: ["hackathon-ui-polish", "hackathon-demo", "landing-blueprint", "dashboard-blueprint"],
    relatedRegistryIds: ["operational-workspace-recipe", "data-story-recipe", "layouts"],
    recommendedFor: ["UX design phase", "Experience architecture"],
    limitations: ["Speed-optimized for hackathon — adapt for full product UX processes"],
  },
  {
    id: "hackathon-video-brag",
    collectionId: "hackathon-ux-ui",
    format: "script",
    phases: ["launch", "submit"],
    audiences: ["video-editor", "demo-producer", "hackathon-builder"],
    outcomes: ["video-production", "social-launch"],
    tags: ["brag", "teaser", "social", "launch", "20-30s", "trailer"],
    maturity: "active",
    ecosystemTarget: "universal-demo-film-kit",
    relatedPlaybookIds: ["hackathon-operating-gates", "hackathon-video-egaki", "demo-video-script"],
    relatedRegistryIds: ["capture-bridge", "broadcast-package-recipe"],
    recommendedFor: ["Social launch teaser", "20-30s brag trailer"],
    limitations: ["Requires frozen demo and UI — not for pre-polish use"],
    futureTarget: "universal-demo-film-kit",
  },
  {
    id: "hackathon-video-egaki",
    collectionId: "hackathon-ux-ui",
    format: "script",
    phases: ["present", "submit"],
    audiences: ["video-editor", "demo-producer", "submission-lead", "hackathon-builder"],
    outcomes: ["video-production", "judge-clarity", "submission"],
    tags: ["egaki", "judge", "video", "60-120s", "structured", "submission"],
    maturity: "active",
    ecosystemTarget: "universal-demo-film-kit",
    relatedPlaybookIds: ["hackathon-operating-gates", "hackathon-video-brag", "demo-video-script", "hackathon-demo"],
    relatedRegistryIds: ["capture-bridge", "interaction-player", "broadcast-package-recipe"],
    recommendedFor: ["60-120s structured submission video", "Judge-facing video packaging"],
    limitations: ["Video truth rules are mandatory — no fake metrics or fake live integrations"],
    futureTarget: "universal-demo-film-kit",
  },
  {
    id: "hackathon-visual-production",
    collectionId: "hackathon-ux-ui",
    format: "operating-module",
    phases: ["build", "present"],
    audiences: ["creative-director", "ui-designer", "demo-producer", "hackathon-builder"],
    outcomes: ["visual-direction", "video-production", "judge-clarity"],
    tags: ["visual-production", "production", "assets", "brand", "identity", "video"],
    maturity: "active",
    ecosystemTarget: "universal-demo-film-kit",
    relatedPlaybookIds: ["hackathon-demo", "hackathon-ui-polish", "controlled-visual-risk", "judge-visual-moment"],
    relatedRegistryIds: ["product-launch-recipe", "broadcast-package-recipe"],
    recommendedFor: ["Visual production pipeline", "Asset creation for submission"],
    limitations: ["Production scope must be realistic within hackathon time constraints"],
    futureTarget: "universal-demo-film-kit",
  },
]

// Build the ID → publicTargetPath mapping from the manifest
// We derive slug/slugSegments from the publicTargetPath in catalog.ts
// to avoid duplicating the path here.

// Exported map: id → overlay (without slug, added in catalog.ts)
export const playbookMetadataMap = new Map<string, OverlayInput>(
  rawOverlays.map((o) => [o.id, o])
)

// Exported as array for iteration
export const playbookMetadataOverlays: readonly OverlayInput[] = rawOverlays

// ID set for quick lookup
export const KNOWN_PLAYBOOK_IDS = new Set(rawOverlays.map((o) => o.id))
