import type { DirectorFixture, SkillMetadata } from "./types"
import { projectPresets } from "../projects/presets"

const baseSkills: SkillMetadata[] = [
  {
    skillId: "director-core-readonly",
    title: "Director Core Readonly",
    description: "Deterministic analysis and read-only director evaluation.",
    version: "1.0.0",
    provenance: "local-fixture",
    supportedModes: ["DAY_CHALLENGE", "HACKATHON", "MARA", "DATA_STORY"],
    supportedPhases: ["intake", "clarify", "route", "build", "verify", "review", "submit", "publish"],
    activationConditions: ["project available"],
    requiredInputs: ["canonical project", "authority context"],
    producedOutputs: ["director result"],
    dependencies: [],
    conflicts: [],
    authorityRequirement: "suggest",
    maturity: "approved",
    loadingPolicy: "metadata-first",
    sourcePaths: ["lib/director"],
    status: "available",
  },
]

export const directorFixtures: Record<string, DirectorFixture> = {
  "the-second-absence": {
    project: {
      ...projectPresets[0],
      id: "the-second-absence",
      title: "The Second Absence",
      shortTitle: "Second Absence",
      nextActions: [
        {
          id: "act-day-1",
          label: "Validate hypothesis lock proof",
          description: "Verify the cryptographic commitment lever and client receipt before final single-day demo capture.",
          phase: "build",
          status: "todo",
        },
      ],
    },
    mode: "DAY_CHALLENGE",
    phaseContext: "build",
    evaluationTimestamp: "2026-08-06T12:00:00Z",
    lockedDecisions: [],
    learningProposals: [],
    authorityContext: {
      authorityLevel: "suggest",
      requestedAction: "analyze",
      target: "the-second-absence",
      reversibility: "reversible",
      risk: "low",
      approvalRequirement: "none",
      grantedScope: ["analysis"],
      status: "granted",
    },
    availableSkills: baseSkills,
    evidence: [],
  },
  "cleanverse-build-round-2": {
    project: {
      ...projectPresets[0],
      id: "cleanverse-build-round-2",
      title: "Cleanverse Build Round 2",
      shortTitle: "Cleanverse Build",
      blockers: ["Hackathon submission gate requires verified audit log proof and zero unhandled session loss warnings."],
      nextActions: [
        {
          id: "act-hackathon-1",
          label: "Resolve hackathon audit receipt blocker",
          description: "Resolve session reset loss warning and verify audit receipt generator for judge evaluation.",
          phase: "verify",
          status: "blocked",
        },
      ],
    },
    mode: "HACKATHON",
    phaseContext: "verify",
    evaluationTimestamp: "2026-08-06T12:00:00Z",
    lockedDecisions: [],
    learningProposals: [],
    authorityContext: {
      authorityLevel: "prepare",
      requestedAction: "prepare submission",
      target: "cleanverse-build-round-2",
      reversibility: "reversible",
      risk: "medium",
      approvalRequirement: "explicit",
      grantedScope: ["prepare"],
      status: "granted",
    },
    availableSkills: baseSkills,
    evidence: [],
  },
  "mara-episode": {
    project: {
      ...projectPresets[2],
      id: "mara-episode",
      title: "MARA Episode",
      shortTitle: "MARA Episode",
      nextActions: [
        {
          id: "act-mara-1",
          label: "Resolve Eight-Bar Hole score continuity",
          description: "Review narrative continuity and verify missing letter C score transposition before audience delivery.",
          phase: "design",
          status: "todo",
        },
      ],
    },
    mode: "MARA",
    phaseContext: "design",
    evaluationTimestamp: "2026-08-06T12:00:00Z",
    lockedDecisions: [],
    learningProposals: [],
    authorityContext: {
      authorityLevel: "suggest",
      requestedAction: "review continuity",
      target: "mara-episode",
      reversibility: "reversible",
      risk: "low",
      approvalRequirement: "none",
      grantedScope: ["analysis"],
      status: "granted",
    },
    availableSkills: baseSkills,
    evidence: [],
  },
  "power-bi-service-performance": {
    project: {
      ...projectPresets[2],
      id: "power-bi-service-performance",
      title: "Power BI Service Performance",
      shortTitle: "Power BI Service",
      nextActions: [
        {
          id: "act-datastory-1",
          label: "Validate Power BI metric evidence",
          description: "Validate controlling SVG performance metric evidence and clarify stakeholder decision criteria.",
          phase: "verify",
          status: "todo",
        },
      ],
    },
    mode: "DATA_STORY",
    phaseContext: "verify",
    evaluationTimestamp: "2026-08-06T12:00:00Z",
    lockedDecisions: [],
    learningProposals: [],
    authorityContext: {
      authorityLevel: "suggest",
      requestedAction: "inspect metric evidence",
      target: "power-bi-service-performance",
      reversibility: "reversible",
      risk: "low",
      approvalRequirement: "none",
      grantedScope: ["analysis"],
      status: "granted",
    },
    availableSkills: baseSkills,
    evidence: [],
  },
}
