import type { DirectorFixture, SkillMetadata } from "./types"
import { projectPresets } from "../projects/presets"

const baseSkills: SkillMetadata[] = [
  {
    skillId: "director-core-readonly",
    title: "Director Core Readonly",
    description: "Deterministic analysis and read-only director evaluation.",
    version: "1.0.0",
    provenance: "local-fixture",
    supportedModes: ["DAY_CHALLENGE", "HACKATHON", "MARA", "DATA_STORY"],
    supportedPhases: ["intake", "clarify", "route", "build", "verify", "review", "submit", "publish"],
    activationConditions: ["project available"],
    requiredInputs: ["canonical project", "authority context"],
    producedOutputs: ["director result"],
    dependencies: [],
    conflicts: [],
    authorityRequirement: "suggest",
    maturity: "approved",
    loadingPolicy: "metadata-first",
    sourcePaths: ["lib/director"],
    status: "available",
  },
]

export const directorFixtures: Record<string, DirectorFixture> = {
  "the-second-absence": {
    project: projectPresets[0],
    mode: "DAY_CHALLENGE",
    phaseContext: "build",
    evaluationTimestamp: "2026-08-06T12:00:00Z",
    lockedDecisions: [],
    learningProposals: [],
    authorityContext: {
      authorityLevel: "suggest",
      requestedAction: "analyze",
      target: "the-second-absence",
      reversibility: "reversible",
      risk: "low",
      approvalRequirement: "none",
      grantedScope: ["analysis"],
      status: "granted",
    },
    availableSkills: baseSkills,
    evidence: [],
  },
  "cleanverse-build-round-2": {
    project: projectPresets[0],
    mode: "HACKATHON",
    phaseContext: "verify",
    evaluationTimestamp: "2026-08-06T12:00:00Z",
    lockedDecisions: [],
    learningProposals: [],
    authorityContext: {
      authorityLevel: "prepare",
      requestedAction: "prepare submission",
      target: "cleanverse-build-round-2",
      reversibility: "reversible",
      risk: "medium",
      approvalRequirement: "explicit",
      grantedScope: ["prepare"],
      status: "granted",
    },
    availableSkills: baseSkills,
    evidence: [],
  },
  "mara-episode": {
    project: projectPresets[2],
    mode: "MARA",
    phaseContext: "design",
    evaluationTimestamp: "2026-08-06T12:00:00Z",
    lockedDecisions: [],
    learningProposals: [],
    authorityContext: {
      authorityLevel: "suggest",
      requestedAction: "review continuity",
      target: "mara-episode",
      reversibility: "reversible",
      risk: "low",
      approvalRequirement: "none",
      grantedScope: ["analysis"],
      status: "granted",
    },
    availableSkills: baseSkills,
    evidence: [],
  },
  "power-bi-service-performance": {
    project: projectPresets[2],
    mode: "DATA_STORY",
    phaseContext: "verify",
    evaluationTimestamp: "2026-08-06T12:00:00Z",
    lockedDecisions: [],
    learningProposals: [],
    authorityContext: {
      authorityLevel: "suggest",
      requestedAction: "inspect metric evidence",
      target: "power-bi-service-performance",
      reversibility: "reversible",
      risk: "low",
      approvalRequirement: "none",
      grantedScope: ["analysis"],
      status: "granted",
    },
    availableSkills: baseSkills,
    evidence: [],
  },
}


