import type { FontProfile } from "@/lib/typography/types"

export const fontProfiles: FontProfile[] = [
  {
    family: "Inter",
    displayName: "Inter",
    role: "body",
    source: "google-font",
    licenseStatus: "confirmed",
    licenseName: "Open Font License",
    provenance: "Loaded via next/font/google in app/layout.tsx",
    variable: "--font-sans",
    weights: [400, 500, 600, 700],
    styles: ["normal", "italic"],
    fallbackStack: 'var(--font-sans), "Segoe UI", Arial, sans-serif',
    supportedScripts: ["Latin"],
    recommendedUses: ["Longform body copy", "Controls", "Utility text"],
    limitations: ["Latin-focused in this project", "Not a bespoke brand font"],
    cssVariable: "--font-sans",
  },
  {
    family: "Geist",
    displayName: "Geist Sans",
    role: "editorial-heading",
    source: "google-font",
    licenseStatus: "confirmed",
    licenseName: "Open Font License",
    provenance: "Loaded via next/font/google in app/layout.tsx",
    variable: "--font-geist-sans",
    weights: [400, 500, 600, 700],
    styles: ["normal", "italic"],
    fallbackStack: 'var(--font-geist-sans), var(--font-sans), sans-serif',
    supportedScripts: ["Latin"],
    recommendedUses: ["Editorial headings", "Launch statements", "Section titles"],
    limitations: ["Variable fonts are not sourced from a dedicated brand package"],
    cssVariable: "--font-geist-sans",
  },
  {
    family: "Geist Mono",
    displayName: "Geist Mono",
    role: "numeric",
    source: "google-font",
    licenseStatus: "confirmed",
    licenseName: "Open Font License",
    provenance: "Loaded via next/font/google in app/layout.tsx",
    variable: "--font-geist-mono",
    weights: [400, 500, 600, 700],
    styles: ["normal"],
    fallbackStack: 'var(--font-geist-mono), "SFMono-Regular", Consolas, monospace',
    supportedScripts: ["Latin"],
    recommendedUses: ["Labels", "Counters", "Captions", "Selectors"],
    limitations: ["Best used for short strings and metadata"],
    cssVariable: "--font-geist-mono",
  },
]
