// ─────────────────────────────────────────────────────────────
// Data & Decision Components — Scenarios & Presets
// ─────────────────────────────────────────────────────────────

import type { DecisionScenario } from "./types"

// ─────────────────────────────────────────────────────────────
// 1. RELEASE READINESS (Main Scenario)
// ─────────────────────────────────────────────────────────────
export const releaseReadinessScenario: DecisionScenario = {
  id: "release-readiness",
  label: "Release Readiness",
  description: "Evaluate deployment candidate eligibility based on automated test suite, target defects, rollback logs, and compliance gates.",
  question: "Is this release ready to proceed?",
  modes: {
    observed: {
      signals: [
        {
          id: "automated-checks-passed",
          label: "Automated Checks Passed",
          value: 98.4,
          unit: "%",
          status: "normal",
          source: "CI Pipelines",
          timestamp: "09m ago",
          thresholdsDescription: "Must be ≥ 95.0%",
        },
        {
          id: "critical-defects",
          label: "Critical Defects Count",
          value: 0,
          status: "normal",
          source: "Jira / Bug Tracker",
          timestamp: "02m ago",
          thresholdsDescription: "Must be = 0",
        },
        {
          id: "unresolved-warnings",
          label: "Unresolved Code Warnings",
          value: 12,
          status: "warning",
          source: "SonarQube Scan",
          timestamp: "12m ago",
          thresholdsDescription: "Must be < 15 for normal, ≥ 15 blocks",
        },
        {
          id: "rollback-logs-freshness",
          label: "Rollback Verification",
          value: true,
          status: "normal",
          source: "Chaos Monkey Simulator",
          timestamp: "1h ago",
          thresholdsDescription: "Must be True",
        },
      ],
      evidence: [
        {
          id: "automated-tests-log",
          label: "Pipeline Test Execution Log",
          source: "GitHub Actions run #842",
          direction: "supports",
          strength: "strong",
          status: "available",
          date: "Jul 25, 2026",
          affectedRuleIds: ["automated-checks-rule"],
        },
        {
          id: "security-audit-seal",
          label: "Static Application Security Seal",
          source: "Snyk Security Audits",
          direction: "supports",
          strength: "moderate",
          status: "available",
          date: "Jul 24, 2026",
          affectedRuleIds: ["unresolved-warnings-rule"],
        },
        {
          id: "rollback-simulation-evidence",
          label: "Rollback Verified Stamp",
          source: "Release Engineering Team",
          direction: "supports",
          strength: "strong",
          status: "available",
          date: "Jul 25, 2026",
          affectedRuleIds: ["rollback-verified-rule"],
        },
      ],
    },
    stress: {
      signals: [
        {
          id: "automated-checks-passed",
          label: "Automated Checks Passed",
          value: 91.2,
          unit: "%",
          status: "warning",
          source: "CI Pipelines",
          timestamp: "1m ago",
          thresholdsDescription: "Must be ≥ 95.0%",
        },
        {
          id: "critical-defects",
          label: "Critical Defects Count",
          value: 3,
          status: "critical",
          source: "Jira / Bug Tracker",
          timestamp: "0m ago",
          thresholdsDescription: "Must be = 0",
        },
        {
          id: "unresolved-warnings",
          label: "Unresolved Code Warnings",
          value: 48,
          status: "critical",
          source: "SonarQube Scan",
          timestamp: "5m ago",
          thresholdsDescription: "Must be < 15 for normal, ≥ 15 blocks",
        },
        {
          id: "rollback-logs-freshness",
          label: "Rollback Verification",
          value: false,
          status: "critical",
          source: "Chaos Monkey Simulator",
          timestamp: "2h ago",
          thresholdsDescription: "Must be True",
        },
      ],
      evidence: [
        {
          id: "automated-tests-log",
          label: "Pipeline Test Execution Log",
          source: "GitHub Actions run #843",
          direction: "supports",
          strength: "strong",
          status: "disputed",
          date: "Jul 25, 2026",
          affectedRuleIds: ["automated-checks-rule"],
        },
        {
          id: "security-audit-seal",
          label: "Static Application Security Seal",
          source: "Snyk Security Audits",
          direction: "contradicts",
          strength: "strong",
          status: "available",
          date: "Jul 25, 2026",
          affectedRuleIds: ["unresolved-warnings-rule"],
        },
        {
          id: "rollback-simulation-evidence",
          label: "Rollback Verified Stamp",
          source: "Release Engineering Team",
          direction: "supports",
          strength: "moderate",
          status: "missing",
          date: "—",
          affectedRuleIds: ["rollback-verified-rule"],
        },
      ],
    },
    edge: {
      signals: [
        {
          id: "automated-checks-passed",
          label: "Automated Checks Passed",
          value: 95.0,
          unit: "%",
          status: "normal",
          source: "CI Pipelines",
          timestamp: "30m ago",
          thresholdsDescription: "Must be ≥ 95.0%",
        },
        {
          id: "critical-defects",
          label: "Critical Defects Count",
          value: 0,
          status: "normal",
          source: "Jira / Bug Tracker",
          timestamp: "10m ago",
          thresholdsDescription: "Must be = 0",
        },
        {
          id: "unresolved-warnings",
          label: "Unresolved Code Warnings",
          value: 14,
          status: "warning",
          source: "SonarQube Scan",
          timestamp: "45m ago",
          thresholdsDescription: "Must be < 15 for normal, ≥ 15 blocks",
        },
        {
          id: "rollback-logs-freshness",
          label: "Rollback Verification",
          value: null,
          status: "unknown",
          source: "Chaos Monkey Simulator",
          timestamp: "—",
          thresholdsDescription: "Must be True",
        },
      ],
      evidence: [
        {
          id: "automated-tests-log",
          label: "Pipeline Test Execution Log",
          source: "GitHub Actions run #844",
          direction: "supports",
          strength: "strong",
          status: "available",
          date: "Jul 25, 2026",
          affectedRuleIds: ["automated-checks-rule"],
        },
        {
          id: "security-audit-seal",
          label: "Static Application Security Seal",
          source: "Snyk Security Audits",
          direction: "supports",
          strength: "moderate",
          status: "available",
          date: "Jul 25, 2026",
          affectedRuleIds: ["unresolved-warnings-rule"],
        },
        {
          id: "rollback-simulation-evidence",
          label: "Rollback Verified Stamp",
          source: "Release Engineering Team",
          direction: "supports",
          strength: "strong",
          status: "missing",
          date: "—",
          affectedRuleIds: ["rollback-verified-rule"],
        },
      ],
    },
  },
  rules: [
    {
      id: "automated-checks-rule",
      label: "CI Pipeline Coverage Threshold",
      condition: {
        signalId: "automated-checks-passed",
        operator: "greater-than-or-equal",
        value: 95.0,
      },
      status: "pass",
      weight: 2,
      affectedEvidenceIds: ["automated-tests-log"],
      consequence: "Pipeline failures block deployment to preserve system integrity.",
      changeConditionDescription: "Requires automated CI checks score to meet or exceed 95.0%.",
    },
    {
      id: "critical-defects-rule",
      label: "Zero Critical Defects Requirement",
      condition: {
        signalId: "critical-defects",
        operator: "equals",
        value: 0,
      },
      status: "pass",
      weight: 3,
      affectedEvidenceIds: [],
      consequence: "Active critical defects block the gate immediately.",
      changeConditionDescription: "Resolve and close all critical bug tickets.",
    },
    {
      id: "unresolved-warnings-rule",
      label: "Code Warning Level Integrity",
      condition: {
        signalId: "unresolved-warnings",
        operator: "less-than",
        value: 15,
      },
      status: "pass",
      weight: 1,
      affectedEvidenceIds: ["security-audit-seal"],
      consequence: "Excessive warnings require static analysis manual verification.",
      changeConditionDescription: "Reduce static analysis warnings count below 15.",
    },
    {
      id: "rollback-verified-rule",
      label: "Deterministic Rollback Log Verification",
      condition: {
        signalId: "rollback-logs-freshness",
        operator: "equals",
        value: true,
      },
      status: "pass",
      weight: 2,
      affectedEvidenceIds: ["rollback-simulation-evidence"],
      consequence: "Failing rollback simulator verification blocks candidate.",
      changeConditionDescription: "Verify that rollback procedure passes simulations.",
    },
  ],
  configurableThresholds: [
    {
      id: "automated-checks-passed",
      label: "Minimum Pipeline Pass Score",
      value: 95.0,
      defaultValue: 95.0,
      min: 80.0,
      max: 100.0,
      step: 0.5,
      unit: "%",
    },
    {
      id: "unresolved-warnings",
      label: "Max Unresolved Warnings",
      value: 15,
      defaultValue: 15,
      min: 5,
      max: 50,
      step: 1,
    },
  ],
  outcomeMapping: {
    "proceed:approved": {
      outcome: "proceed",
      status: "approved",
      recommendation: "Approved to deploy. Triggers deployment execution pipeline automatically.",
    },
    "hold:pending": {
      outcome: "hold",
      status: "pending",
      recommendation: "System is on HOLD. Rollback simulation evidence or critical signal is missing/disputed.",
    },
    "review:review": {
      outcome: "review",
      status: "review",
      recommendation: "Manual team validation required. Lower severity threshold warning rule failed.",
    },
    "reject:blocked": {
      outcome: "reject",
      status: "blocked",
      recommendation: "Candidate rejected. High severity defects or pipeline failures present in scope.",
    },
    "insufficient-evidence:insufficient": {
      outcome: "insufficient-evidence",
      status: "insufficient",
      recommendation: "Insufficient Evidence. A critical evidence file is missing or manually excluded.",
    },
  },
  limitations: [
    "Evaluations are based on passive telemetry data limits.",
    "No runtime environment capability verified during this phase.",
    "This tool is for demonstration, not legal regulatory audit approval.",
  ],
}

// ─────────────────────────────────────────────────────────────
// 2. SERVICE ESCALATION
// ─────────────────────────────────────────────────────────────
export const serviceEscalationScenario: DecisionScenario = {
  id: "service-escalation",
  label: "Service Escalation",
  description: "Determine if an active infrastructure issue warrants high-level engineering alert escalation.",
  question: "Should this service issue be escalated?",
  modes: {
    observed: {
      signals: [
        {
          id: "failure-count",
          label: "Failure Rate Log",
          value: 4,
          status: "warning",
          source: "Datadog API",
          timestamp: "1m ago",
          thresholdsDescription: "Escalates if failure rate is ≥ 5",
        },
        {
          id: "affected-users",
          label: "Affected Users Reach",
          value: 840,
          status: "normal",
          source: "Telemetry Metrics",
          timestamp: "0m ago",
          thresholdsDescription: "Escalates if affected users exceed 1000",
        },
      ],
      evidence: [
        {
          id: "escalation-playbook",
          label: "On-Call Escalation Playbook",
          source: "Platform Engineering Docs",
          direction: "supports",
          strength: "strong",
          status: "available",
          date: "Jul 10, 2026",
          affectedRuleIds: ["failure-count-rule"],
        },
      ],
    },
    stress: {
      signals: [
        {
          id: "failure-count",
          label: "Failure Rate Log",
          value: 12,
          status: "critical",
          source: "Datadog API",
          timestamp: "0m ago",
          thresholdsDescription: "Escalates if failure rate is ≥ 5",
        },
        {
          id: "affected-users",
          label: "Affected Users Reach",
          value: 8500,
          status: "critical",
          source: "Telemetry Metrics",
          timestamp: "0m ago",
          thresholdsDescription: "Escalates if affected users exceed 1000",
        },
      ],
      evidence: [
        {
          id: "escalation-playbook",
          label: "On-Call Escalation Playbook",
          source: "Platform Engineering Docs",
          direction: "supports",
          strength: "strong",
          status: "available",
          date: "Jul 10, 2026",
          affectedRuleIds: ["failure-count-rule", "affected-users-rule"],
        },
      ],
    },
    edge: {
      signals: [
        {
          id: "failure-count",
          label: "Failure Rate Log",
          value: 5,
          status: "warning",
          source: "Datadog API",
          timestamp: "2m ago",
          thresholdsDescription: "Escalates if failure rate is ≥ 5",
        },
        {
          id: "affected-users",
          label: "Affected Users Reach",
          value: 1000,
          status: "warning",
          source: "Telemetry Metrics",
          timestamp: "1m ago",
          thresholdsDescription: "Escalates if affected users exceed 1000",
        },
      ],
      evidence: [
        {
          id: "escalation-playbook",
          label: "On-Call Escalation Playbook",
          source: "Platform Engineering Docs",
          direction: "supports",
          strength: "strong",
          status: "missing",
          date: "—",
          affectedRuleIds: ["failure-count-rule"],
        },
      ],
    },
  },
  rules: [
    {
      id: "failure-count-rule",
      label: "Rate Alert Scale",
      condition: {
        signalId: "failure-count",
        operator: "greater-than-or-equal",
        value: 5,
      },
      status: "fail",
      weight: 2,
      affectedEvidenceIds: ["escalation-playbook"],
      consequence: "Triggers incident escalation alert if threshold is crossed.",
      changeConditionDescription: "Requires failure count to be below 5.",
    },
    {
      id: "affected-users-rule",
      label: "Affected User Limit",
      condition: {
        signalId: "affected-users",
        operator: "greater-than",
        value: 1000,
      },
      status: "fail",
      weight: 3,
      affectedEvidenceIds: [],
      consequence: "Severe volume breach triggers alert escalation automatically.",
      changeConditionDescription: "Requires affected user scope to drop under 1000.",
    },
  ],
  configurableThresholds: [
    {
      id: "failure-count",
      label: "Trigger Failure Count Limit",
      value: 5,
      defaultValue: 5,
      min: 2,
      max: 15,
      step: 1,
    },
  ],
  outcomeMapping: {
    "proceed:approved": {
      outcome: "proceed",
      status: "approved",
      recommendation: "System stable. Normal alert tier handles notifications.",
    },
    "hold:pending": {
      outcome: "hold",
      status: "pending",
      recommendation: "Requires manual check. Alert count met but escalation playbook missing.",
    },
    "review:review": {
      outcome: "review",
      status: "review",
      recommendation: "Minor incident. Watch metrics continuously.",
    },
    "reject:blocked": {
      outcome: "reject",
      status: "blocked",
      recommendation: "Incident ESCALATED. Major telemetry limits breached.",
    },
    "insufficient-evidence:insufficient": {
      outcome: "insufficient-evidence",
      status: "insufficient",
      recommendation: "Verification criteria missing. Alert team directly.",
    },
  },
  limitations: [
    "Escalation recommendation is advisory only.",
    "Alert logic relies on operational metrics logs from providers.",
  ],
}

// ─────────────────────────────────────────────────────────────
// 3. COMPLIANCE REVIEW
// ─────────────────────────────────────────────────────────────
export const complianceReviewScenario: DecisionScenario = {
  id: "compliance-review",
  label: "Compliance Review",
  description: "Verify if document check meets operational safety and internal review guidelines.",
  question: "Can this item pass the review gate?",
  modes: {
    observed: {
      signals: [
        {
          id: "required-docs-verified",
          label: "Required Documents Filed",
          value: true,
          status: "normal",
          source: "Legal Portal",
          timestamp: "24h ago",
          thresholdsDescription: "Must be True",
        },
        {
          id: "unresolved-exceptions",
          label: "Exceptions Reported",
          value: 0,
          status: "normal",
          source: "Safety Check Audit",
          timestamp: "2h ago",
          thresholdsDescription: "Must be = 0",
        },
      ],
      evidence: [
        {
          id: "legal-clearance-doc",
          label: "Signed Legal Review File",
          source: "Legal Operations Portal",
          direction: "supports",
          strength: "strong",
          status: "available",
          date: "Jul 23, 2026",
          affectedRuleIds: ["required-docs-rule"],
        },
      ],
    },
    stress: {
      signals: [
        {
          id: "required-docs-verified",
          label: "Required Documents Filed",
          value: false,
          status: "critical",
          source: "Legal Portal",
          timestamp: "0m ago",
          thresholdsDescription: "Must be True",
        },
        {
          id: "unresolved-exceptions",
          label: "Exceptions Reported",
          value: 4,
          status: "critical",
          source: "Safety Check Audit",
          timestamp: "1m ago",
          thresholdsDescription: "Must be = 0",
        },
      ],
      evidence: [
        {
          id: "legal-clearance-doc",
          label: "Signed Legal Review File",
          source: "Legal Operations Portal",
          direction: "contradicts",
          strength: "strong",
          status: "available",
          date: "Jul 25, 2026",
          affectedRuleIds: ["required-docs-rule"],
        },
      ],
    },
    edge: {
      signals: [
        {
          id: "required-docs-verified",
          label: "Required Documents Filed",
          value: true,
          status: "normal",
          source: "Legal Portal",
          timestamp: "1h ago",
          thresholdsDescription: "Must be True",
        },
        {
          id: "unresolved-exceptions",
          label: "Exceptions Reported",
          value: 1,
          status: "warning",
          source: "Safety Check Audit",
          timestamp: "10m ago",
          thresholdsDescription: "Must be = 0",
        },
      ],
      evidence: [
        {
          id: "legal-clearance-doc",
          label: "Signed Legal Review File",
          source: "Legal Operations Portal",
          direction: "supports",
          strength: "strong",
          status: "missing",
          date: "—",
          affectedRuleIds: ["required-docs-rule"],
        },
      ],
    },
  },
  rules: [
    {
      id: "required-docs-rule",
      label: "Filing Document Check",
      condition: {
        signalId: "required-docs-verified",
        operator: "equals",
        value: true,
      },
      status: "pass",
      weight: 3,
      affectedEvidenceIds: ["legal-clearance-doc"],
      consequence: "Missing required documents blocks filing process.",
      changeConditionDescription: "Requires all mandatory legal documents to be filed.",
    },
    {
      id: "exceptions-rule",
      label: "Safety Exception Limit",
      condition: {
        signalId: "unresolved-exceptions",
        operator: "equals",
        value: 0,
      },
      status: "pass",
      weight: 2,
      affectedEvidenceIds: [],
      consequence: "Active audit exceptions require senior safety approval.",
      changeConditionDescription: "Resolve and log clearances for exceptions.",
    },
  ],
  configurableThresholds: [],
  outcomeMapping: {
    "proceed:approved": {
      outcome: "proceed",
      status: "approved",
      recommendation: "Compliance approved. Item satisfies review criteria.",
    },
    "hold:pending": {
      outcome: "hold",
      status: "pending",
      recommendation: "Pending additional documentation. Check submission statuses.",
    },
    "review:review": {
      outcome: "review",
      status: "review",
      recommendation: "Item contains warning issues. Requires secondary sign-off.",
    },
    "reject:blocked": {
      outcome: "reject",
      status: "blocked",
      recommendation: "Item fails compliance. Fix audit exceptions directly.",
    },
    "insufficient-evidence:insufficient": {
      outcome: "insufficient-evidence",
      status: "insufficient",
      recommendation: "Critical legal review signature file is missing.",
    },
  },
  limitations: [
    "Subject to compliance rules updating schedules.",
    "System does not provide real compliance certification.",
  ],
}

export const decisionPresets = {
  releaseReadiness: releaseReadinessScenario,
  serviceEscalation: serviceEscalationScenario,
  complianceReview: complianceReviewScenario,
} as const
